apiVersion: v1
kind: Pod
metadata:
  name: nginx
    #  namespace: devops
  labels:
    app: nginx-run
spec:
  containers:
  - name: nginx
    imagePullPolicy: IfNotPresent
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  
