apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
#  namespace: kube-system
  labels:
    k8s-app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana
  template:
    metadata:
      labels:
        k8s-app: kibana
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: http://192.168.202.121:30683
        name: kibana
        image: kibana:7.7.0
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP