apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-07-06T13:39:07Z"
  labels:
    app: elasticsearch
  name: elasticsearch-svc
  namespace: default
spec:
  clusterIP: 10.111.40.227
  clusterIPs:
  - 10.111.40.227
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30683
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: elasticsearch
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}