apiVersion: v1
kind: Secret
metadata:
  name: cb-example-auth
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg== # Administrator
  password: cGFzc3dvcmQ=         # password
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: content
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-cluster
spec:
  image: couchbase/server:7.0.2
  security:
    adminSecret: cb-example-auth
      #  buckets:
      #    managed: true
  servers:
  - size: 1
    name: all_services
    services:
    - data
    - index
    - query
    - search
      #    - eventing
      #    - analytics
    volumeMounts:
      default: couchbase
  backup:
    managed: true 
    image: couchbase/operator-backup:1.3.0 
    serviceAccountName: couchbase-backup     
    s3Secret: s3-secret
    objectEndpoint:
      #      url: http://192.168.1.15:9000
      url: https://dev-files.semanoor.com
  volumeClaimTemplates: 
  - metadata:
      name: couchbase 
    spec:
      #      storageClassName: standard 
      resources: 
        requests:
          storage: 1Gi
