apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backupdir-graphdb-neo4j-core-0
spec:
  #storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 05Gi