apiVersion: couchbase.com/v2
kind: CouchbaseBackupRestore
metadata:
  name: my-restore
spec:
  backup: my-backup
  repo: cb-cluster-2022-06-17T10_45_05
  start:
    str: 2022-06-17T10_45_05.925287023Z
  end:
    str: 2022-06-17T10_45_05.925287023Z