apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 32000
    name: web
  clusterIP: 
  selector:
    app: nginx
  type: NodePort
